[package]
name = "slog-bunyan"
version = "1.1.1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Bunyan formatter for slog-rs"
keywords = ["log", "logging", "structured", "hierarchical"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-bunyan"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/bunyan"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "1.1"
slog-json = "1"
nix = "0.6.0"
chrono = "0.2.22"

[dev-dependencies]
slog-stream = "1.2"
